baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'iSite'

[params]
slogan = 'Super simple theme for Hugo'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
